# Generated by Django 5.0.2 on 2024-03-03 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(choices=[('C', 'Creación'), ('M', 'Modificación'), ('E', 'Eliminación')], max_length=1)),
                ('tabla', models.CharField(max_length=255)),
                ('dato_modificado', models.TextField()),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('numero_documento', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id_subsidio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_alta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('BA', 'Baja')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidioDetalle',
            fields=[
                ('id_subsidio_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
