# Generated by Django 5.0.2 on 2024-03-03 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidiosapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsidio',
            name='oficina_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subsidiosapp.oficina'),
        ),
        migrations.AddField(
            model_name='subsidiodetalle',
            name='id_beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiosapp.beneficiario'),
        ),
        migrations.AddField(
            model_name='subsidiodetalle',
            name='id_subsidio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiosapp.subsidio'),
        ),
    ]
